"""Write the generated pages of the API reference site, and its pages' Markdown copies.

Usage: docs_pages.py pages [--docs-dir DIR]
       docs_pages.py copies [--docs-dir DIR] [--site-dir DIR]

`pages`, before the site is built, writes into the docs directory (docs/ by default):

- reference/tools.md: every tool with its description, annotations, and input and output
  schemas, as a server built by `create_server` lists them over MCP;
- llms.txt: the site's pages, in the format of https://llmstxt.org, each linked by its
  Markdown copy, or the Embedding API page by its HTML.

`copies`, after the site is built, writes the Markdown of each page whose source is Markdown
as index.md beside the page's index.html in the site directory (site/ by default): the README
for the overview (the snippet includes of docs/index.md expanded), and the Tools page and the
upgrade guide as they are. The Embedding API page is rendered from docstrings, so it has no
copy, and llms.txt links its HTML. A relative link to another page becomes a link to that
page's copy, or to the API page's HTML.

All of it is build output and is not committed. mkdocs.yml's `nav` must list `PAGES`;
tests/test_docs_pages.py checks that it does.
"""

import argparse
import asyncio
import json
import posixpath
import re
import sys
from pathlib import Path
from typing import Any

from mcp.client import Client

from permit_mcp import TOOL_NAMES, Settings, create_server

ROOT = Path(__file__).resolve().parent.parent
SITE_URL = "https://permitio.github.io/permit-mcp/"
GUIDES_URL = "https://docs.permit.io/ai-security/access-request-mcp/overview"
# The settings the tool descriptions are shown with, as in the README's tools table.
SHOWN_SETTINGS = {"resource": "documents", "tenant": "default"}
# Each page of the site, in nav order: its source in the docs directory, its title, and what
# llms.txt says it holds.
PAGES = (
    (
        "index.md",
        "Overview",
        (
            "The README: what the server does, who the acting user is, configuration, the "
            "tools, embedding, errors."
        ),
    ),
    (
        "reference/api.md",
        "Embedding API",
        (
            "create_server, PermitTools, Settings, the identity resolvers and the errors, from "
            "their docstrings."
        ),
    ),
    (
        "reference/tools.md",
        "Tools",
        "Every tool's description, annotations, and input and output JSON schemas.",
    ),
    ("upgrade-to-1.0.md", "Upgrading to 1.0", "What to change when moving from 0.1 to 1.0."),
)
# The page mkdocstrings renders from the docstrings of permit_mcp's exports: its source is
# `:::` entries, not the Markdown a reader sees, so it gets no Markdown copy.
API_PAGE = "reference/api.md"
GENERATED_NOTE = "<!-- Generated by scripts/docs_pages.py from the server's tool list. -->"
# As pymdownx.snippets reads them, with mkdocs.yml's base_path ["."]: the repository root.
SNIPPET = re.compile(r"""^\s*-+8<-+\s+(["'])(?P<path>[^"']+)\1\s*$""")
# A Markdown link to another page by its source file, such as [Tools](tools.md#x).
RELATIVE_PAGE_LINK = re.compile(
    r"\]\((?P<path>(?![a-z][a-z0-9+.-]*:|/|#)[^)#\s]+\.md)(?P<anchor>#[^)\s]*)?\)"
)


async def list_tools() -> list[dict[str, Any]]:
    """Return the tools a server with every tool registered lists, as MCP sends them."""
    settings = Settings(
        api_key="docs-placeholder-key",
        access_request_element="access-request-element",
        operation_approval_element="operation-approval-element",
        user="docs",
        **SHOWN_SETTINGS,
    )
    async with Client(create_server(settings)) as client:
        tools = (await client.list_tools()).tools
    return [tool.model_dump(by_alias=True, exclude_none=True, mode="json") for tool in tools]


def without_titles(schema: object) -> object:
    """Return a JSON schema without its `title` keywords.

    Pydantic titles a tool's argument and result schemas after the private method that
    implements the tool, which says nothing to a reader. A property that is named "title"
    is kept: in a `properties` mapping the keys are names, not keywords.
    """
    if isinstance(schema, list):
        return [without_titles(item) for item in schema]
    if not isinstance(schema, dict):
        return schema
    kept: dict[str, object] = {}
    for key, value in schema.items():
        if key == "title" and isinstance(value, str):
            continue
        if key in {"properties", "$defs", "definitions"} and isinstance(value, dict):
            kept[key] = {name: without_titles(item) for name, item in value.items()}
        else:
            kept[key] = without_titles(value)
    return kept


def json_block(value: object) -> str:
    """Return `value` as an indented JSON code block, keys sorted."""
    return "```json\n" + json.dumps(value, indent=2, sort_keys=True) + "\n```"


def tools_page(tools: list[dict[str, Any]]) -> str:
    """Render the Tools page from the tools as MCP lists them."""
    lines = [
        "# Tools",
        "",
        GENERATED_NOTE,
        "",
        (
            "The tools as a server lists them over MCP (`tools/list`), in that order. This "
            "server was built with both elements set, "
            f"`PERMIT_RESOURCE={SHOWN_SETTINGS['resource']}` and the "
            f"`{SHOWN_SETTINGS['tenant']}` tenant, which the descriptions name. Which tools a "
            "server registers depends on the elements it is given; see the "
            "[README](../index.md#tools)."
        ),
    ]
    for tool in tools:
        annotations = ", ".join(
            f"`{name}: {json.dumps(value)}`"
            for name, value in sorted(tool.get("annotations", {}).items())
        )
        lines += [
            "",
            f"## `{tool['name']}`",
            "",
            tool.get("description", ""),
            "",
            f"Annotations: {annotations or 'none'}.",
            "",
            "### Input schema",
            "",
            json_block(without_titles(tool["inputSchema"])),
        ]
        if "outputSchema" in tool:
            lines += ["", "### Output schema", "", json_block(without_titles(tool["outputSchema"]))]
    return "\n".join(lines) + "\n"


def page_dir(source: str) -> str:
    """Return the directory, relative to the site, of the page built from `source`.

    The site uses directory URLs: reference/api.md is built as reference/api/index.html.
    """
    path = source.removesuffix(".md")
    if path == "index":
        return ""
    return f"{path.removesuffix('/index')}/"


def page_url(source: str) -> str:
    """Return the published URL of the page built from `source`."""
    return f"{SITE_URL}{page_dir(source)}"


def copy_url(source: str) -> str:
    """Return the published URL of the Markdown copy of the page built from `source`."""
    return f"{page_url(source)}index.md"


def markdown_url(source: str) -> str:
    """Return the URL an agent reads the page built from `source` at.

    That is its Markdown copy, or for the API page, which has none, its HTML.
    """
    return page_url(source) if source == API_PAGE else copy_url(source)


def llms_txt() -> str:
    """Render llms.txt: the project, a summary, and a link to each page."""
    lines = [
        "# permit-mcp",
        "",
        (
            "> An MCP server for Permit.io access requests, operation approvals and permission "
            "checks. This site is its reference: the tools and the Python API for embedding them."
        ),
        "",
        f"Guides are on docs.permit.io: {GUIDES_URL}",
        "",
        "## Docs",
        "",
    ]
    lines += [f"- [{title}]({markdown_url(source)}): {about}" for source, title, about in PAGES]
    lines += [
        "",
        "## Optional",
        "",
        "- [Source](https://github.com/permitio/permit-mcp): the repository, with the changelog",
    ]
    return "\n".join(lines) + "\n"


def expand_snippets(text: str) -> str:
    """Return `text` with each `--8<-- "file"` line replaced by the file, read from ROOT."""
    lines = []
    for line in text.splitlines():
        match = SNIPPET.match(line)
        lines.append((ROOT / match["path"]).read_text(encoding="utf-8") if match else line)
    return "\n".join(lines).rstrip("\n") + "\n"


def link_copies(text: str, source: str) -> str:
    """Point each relative link from page `source` to another page at `markdown_url`."""

    def retarget(match: re.Match[str]) -> str:
        target = posixpath.normpath(posixpath.join(posixpath.dirname(source), match["path"]))
        return f"]({markdown_url(target)}{match['anchor'] or ''})"

    return RELATIVE_PAGE_LINK.sub(retarget, text)


def markdown_copy(source: str, docs_dir: Path) -> str:
    """Return the Markdown copy of the page built from docs_dir/`source`."""
    text = (docs_dir / source).read_text(encoding="utf-8")
    return link_copies(expand_snippets(text), source)


def write_pages(docs_dir: Path) -> None:
    """Write the Tools page and llms.txt into `docs_dir`."""
    tools_md = docs_dir / "reference" / "tools.md"
    tools_md.parent.mkdir(parents=True, exist_ok=True)
    tools = asyncio.run(list_tools())
    listed = tuple(tool["name"] for tool in tools)
    if listed != TOOL_NAMES:
        sys.exit(
            f"docs_pages.py: the server listed the tools {listed}, not TOOL_NAMES {TOOL_NAMES};"
            " the Tools page would not document every tool."
        )
    tools_md.write_text(tools_page(tools), encoding="utf-8")
    (docs_dir / "llms.txt").write_text(llms_txt(), encoding="utf-8")


def write_copies(docs_dir: Path, site_dir: Path) -> None:
    """Write each page's Markdown copy beside its index.html in `site_dir`, but the API page's."""
    for source, _, _ in PAGES:
        if source == API_PAGE:
            continue
        built = site_dir / page_dir(source)
        if not (built / "index.html").is_file():
            sys.exit(f"docs_pages.py: {built / 'index.html'} was not built; build the site first.")
        (built / "index.md").write_text(markdown_copy(source, docs_dir), encoding="utf-8")


def main() -> None:
    """Run the subcommand given on the command line."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    commands = parser.add_subparsers(dest="command", required=True)
    pages = commands.add_parser("pages", help="write the Tools page and llms.txt")
    copies = commands.add_parser("copies", help="write each built page's Markdown copy")
    for command in (pages, copies):
        command.add_argument("--docs-dir", type=Path, default=ROOT / "docs")
    copies.add_argument("--site-dir", type=Path, default=ROOT / "site")
    args = parser.parse_args()
    if args.command == "pages":
        write_pages(args.docs_dir)
    else:
        write_copies(args.docs_dir, args.site_dir)


if __name__ == "__main__":
    main()
