"""Write the generated pages of the API reference site, and its pages' Markdown copies.

Usage: docs_pages.py pages [--docs-dir DIR]
       docs_pages.py copies [--docs-dir DIR] [--site-dir DIR]

`pages`, before the site is built, writes into the docs directory (docs/ by default):

- reference/tools.md: every tool with its description, annotations, and input and output
  schemas, as a server built by `create_server` lists them over MCP;
- llms.txt: the site's pages, in the format of https://llmstxt.org, each linked by its
  Markdown copy.

`copies`, after the site is built, writes each page's Markdown as index.md beside the page's
index.html in the site directory (site/ by default): the README for the overview (the snippet
includes of docs/index.md expanded), the Embedding API with each `::: permit_mcp.NAME` entry
replaced by NAME's signature and docstring, and the Tools page and the upgrade guide as they
are. A relative link to another page becomes a link to that page's copy.

All of it is build output and is not committed. mkdocs.yml's `nav` must list `PAGES`;
tests/test_docs_pages.py checks that it does.
"""

import argparse
import ast
import asyncio
import inspect
import itertools
import json
import posixpath
import re
import sys
from collections.abc import Callable
from pathlib import Path
from typing import Any

from mcp.client import Client

import permit_mcp
from permit_mcp import TOOL_NAMES, Settings, create_server

ROOT = Path(__file__).resolve().parent.parent
SITE_URL = "https://permitio.github.io/permit-mcp/"
GUIDES_URL = "https://docs.permit.io/ai-security/access-request-mcp/overview"
# The settings the tool descriptions are shown with, as in the README's tools table.
SHOWN_SETTINGS = {"resource": "documents", "tenant": "default"}
# Each page of the site, in nav order: its source in the docs directory, its title, and what
# llms.txt says it holds.
PAGES = (
    (
        "index.md",
        "Overview",
        (
            "The README: what the server does, who the acting user is, configuration, the "
            "tools, embedding, errors."
        ),
    ),
    (
        "reference/api.md",
        "Embedding API",
        (
            "create_server, PermitTools, Settings, the identity resolvers and the errors, from "
            "their docstrings."
        ),
    ),
    (
        "reference/tools.md",
        "Tools",
        "Every tool's description, annotations, and input and output JSON schemas.",
    ),
    ("upgrade-to-1.0.md", "Upgrading to 1.0", "What to change when moving from 0.1 to 1.0."),
)
GENERATED_NOTE = "<!-- Generated by scripts/docs_pages.py from the server's tool list. -->"
# As pymdownx.snippets reads them, with mkdocs.yml's base_path ["."]: the repository root.
SNIPPET = re.compile(r"""^\s*-+8<-+\s+(["'])(?P<path>[^"']+)\1\s*$""")
API_ENTRY = re.compile(r"^::: permit_mcp\.(?P<name>\w+)$")
# A Markdown link to another page by its source file, such as [Tools](tools.md#x).
RELATIVE_PAGE_LINK = re.compile(
    r"\]\((?P<path>(?![a-z][a-z0-9+.-]*:|/|#)[^)#\s]+\.md)(?P<anchor>#[^)\s]*)?\)"
)
# The module path before a class name in a signature, such as `permit_mcp.config.` in
# permit_mcp.config.Settings. A default such as 'https://api.permit.io' has none.
MODULE_PATH = re.compile(r"\b(?:[a-z_][a-z0-9_]*\.)+(?=[A-Z])")


async def list_tools() -> list[dict[str, Any]]:
    """Return the tools a server with every tool registered lists, as MCP sends them."""
    settings = Settings(
        api_key="docs-placeholder-key",
        access_request_element="access-request-element",
        operation_approval_element="operation-approval-element",
        user="docs",
        **SHOWN_SETTINGS,
    )
    async with Client(create_server(settings)) as client:
        tools = (await client.list_tools()).tools
    return [tool.model_dump(by_alias=True, exclude_none=True, mode="json") for tool in tools]


def without_titles(schema: object) -> object:
    """Return a JSON schema without its `title` keywords.

    Pydantic titles a tool's argument and result schemas after the private method that
    implements the tool, which says nothing to a reader. A property that is named "title"
    is kept: in a `properties` mapping the keys are names, not keywords.
    """
    if isinstance(schema, list):
        return [without_titles(item) for item in schema]
    if not isinstance(schema, dict):
        return schema
    kept: dict[str, object] = {}
    for key, value in schema.items():
        if key == "title" and isinstance(value, str):
            continue
        if key in {"properties", "$defs", "definitions"} and isinstance(value, dict):
            kept[key] = {name: without_titles(item) for name, item in value.items()}
        else:
            kept[key] = without_titles(value)
    return kept


def json_block(value: object) -> str:
    """Return `value` as an indented JSON code block, keys sorted."""
    return "```json\n" + json.dumps(value, indent=2, sort_keys=True) + "\n```"


def tools_page(tools: list[dict[str, Any]]) -> str:
    """Render the Tools page from the tools as MCP lists them."""
    lines = [
        "# Tools",
        "",
        GENERATED_NOTE,
        "",
        (
            "The tools as a server lists them over MCP (`tools/list`), in that order. This "
            "server was built with both elements set, "
            f"`PERMIT_RESOURCE={SHOWN_SETTINGS['resource']}` and the "
            f"`{SHOWN_SETTINGS['tenant']}` tenant, which the descriptions name. Which tools a "
            "server registers depends on the elements it is given; see the "
            "[README](../index.md#tools)."
        ),
    ]
    for tool in tools:
        annotations = ", ".join(
            f"`{name}: {json.dumps(value)}`"
            for name, value in sorted(tool.get("annotations", {}).items())
        )
        lines += [
            "",
            f"## `{tool['name']}`",
            "",
            tool.get("description", ""),
            "",
            f"Annotations: {annotations or 'none'}.",
            "",
            "### Input schema",
            "",
            json_block(without_titles(tool["inputSchema"])),
        ]
        if "outputSchema" in tool:
            lines += ["", "### Output schema", "", json_block(without_titles(tool["outputSchema"]))]
    return "\n".join(lines) + "\n"


def page_dir(source: str) -> str:
    """Return the directory, relative to the site, of the page built from `source`.

    The site uses directory URLs: reference/api.md is built as reference/api/index.html.
    """
    path = source.removesuffix(".md")
    if path == "index":
        return ""
    return f"{path.removesuffix('/index')}/"


def page_url(source: str) -> str:
    """Return the published URL of the page built from `source`."""
    return f"{SITE_URL}{page_dir(source)}"


def copy_url(source: str) -> str:
    """Return the published URL of the Markdown copy of the page built from `source`."""
    return f"{page_url(source)}index.md"


def llms_txt() -> str:
    """Render llms.txt: the project, a summary, and a link to each page."""
    lines = [
        "# permit-mcp",
        "",
        (
            "> An MCP server for Permit.io access requests, operation approvals and permission "
            "checks. This site is its reference: the tools and the Python API for embedding them."
        ),
        "",
        f"Guides are on docs.permit.io: {GUIDES_URL}",
        "",
        "## Docs",
        "",
    ]
    lines += [f"- [{title}]({copy_url(source)}): {about}" for source, title, about in PAGES]
    lines += [
        "",
        "## Optional",
        "",
        "- [Source](https://github.com/permitio/permit-mcp): the repository, with the changelog",
    ]
    return "\n".join(lines) + "\n"


def expand_snippets(text: str) -> str:
    """Return `text` with each `--8<-- "file"` line replaced by the file, read from ROOT."""
    lines = []
    for line in text.splitlines():
        match = SNIPPET.match(line)
        lines.append((ROOT / match["path"]).read_text(encoding="utf-8") if match else line)
    return "\n".join(lines).rstrip("\n") + "\n"


def signature(function: Callable[..., object]) -> str:
    """Return `function`'s signature without `self` or `cls`, and without module paths."""
    sig = inspect.signature(function)
    parameters = list(sig.parameters.values())
    if parameters and parameters[0].name in {"self", "cls"}:
        sig = sig.replace(parameters=parameters[1:])
    return MODULE_PATH.sub("", str(sig))


def attribute(name: str) -> tuple[str, str]:
    """Return the annotation and docstring of the module-level attribute `name`.

    The docstring is the string right after the assignment in a permit_mcp module, where
    mkdocstrings reads it from too.

    Raises:
        LookupError: No permit_mcp module assigns `name` with an annotation and a docstring.

    """
    for module_name, module in sorted(sys.modules.items()):
        if not module_name.startswith("permit_mcp."):
            continue
        body = ast.parse(inspect.getsource(module)).body
        for node, after in itertools.pairwise(body):
            if (
                isinstance(node, ast.AnnAssign)
                and isinstance(node.target, ast.Name)
                and node.target.id == name
                and isinstance(after, ast.Expr)
                and isinstance(after.value, ast.Constant)
                and isinstance(after.value.value, str)
            ):
                return ast.unparse(node.annotation), inspect.cleandoc(after.value.value)
    msg = f"permit_mcp.{name} is not an annotated attribute with a docstring"
    raise LookupError(msg)


def describe_function(heading: str, name: str, function: Callable[..., object]) -> list[str]:
    """Return the Markdown of a function or method: a heading, its signature, its docstring."""
    keyword = "async def" if inspect.iscoroutinefunction(function) else "def"
    return [
        f"{heading} `{name}`",
        "",
        "```python",
        f"{keyword} {function.__name__}{signature(function)}",
        "```",
        "",
        inspect.getdoc(function) or "",
    ]


def describe(name: str) -> list[str]:
    """Return the Markdown of permit_mcp's export `name`, as the API page shows it.

    A class shows its bases, or its constructor's signature when it has none, its
    docstring, and each public method (and `__call__`) defined on it. A function shows its
    signature and docstring; any other value its annotation, value and docstring.
    """
    value = getattr(permit_mcp, name)
    if inspect.isfunction(value):
        return describe_function("##", name, value)
    if not inspect.isclass(value):
        annotation, doc = attribute(name)
        return [
            f"## `{name}`",
            "",
            "```python",
            f"{name}: {annotation} = {value!r}",
            "```",
            "",
            doc,
        ]
    bases = [base.__name__ for base in value.__bases__ if base is not object]
    shown = f"({', '.join(bases)})" if bases else signature(value).removesuffix(" -> None")
    lines = [f"## `{name}`", "", "```python", f"class {name}{shown}", "```", ""]
    lines.append(inspect.getdoc(value) or "")
    for member_name, member in vars(value).items():
        if member_name.startswith("_") and member_name != "__call__":
            continue
        function = member.__func__ if isinstance(member, classmethod | staticmethod) else member
        if inspect.isfunction(function):
            lines += ["", *describe_function("###", f"{name}.{member_name}", function)]
    return lines


def api_page(text: str) -> str:
    """Return the Embedding API page with each `:::` entry rendered, its options dropped."""
    lines: list[str] = []
    in_entry = False
    for line in text.splitlines():
        if in_entry and line.startswith(" "):
            continue
        match = API_ENTRY.match(line)
        in_entry = match is not None
        lines += describe(match["name"]) if match else [line]
    return "\n".join(lines).rstrip("\n") + "\n"


def link_copies(text: str, source: str) -> str:
    """Point each relative link from page `source` to another page at that page's copy."""

    def to_copy(match: re.Match[str]) -> str:
        target = posixpath.normpath(posixpath.join(posixpath.dirname(source), match["path"]))
        return f"]({copy_url(target)}{match['anchor'] or ''})"

    return RELATIVE_PAGE_LINK.sub(to_copy, text)


def markdown_copy(source: str, docs_dir: Path) -> str:
    """Return the Markdown copy of the page built from docs_dir/`source`."""
    text = (docs_dir / source).read_text(encoding="utf-8")
    if source == "reference/api.md":
        text = api_page(text)
    return link_copies(expand_snippets(text), source)


def write_pages(docs_dir: Path) -> None:
    """Write the Tools page and llms.txt into `docs_dir`."""
    tools_md = docs_dir / "reference" / "tools.md"
    tools_md.parent.mkdir(parents=True, exist_ok=True)
    tools = asyncio.run(list_tools())
    listed = tuple(tool["name"] for tool in tools)
    if listed != TOOL_NAMES:
        sys.exit(
            f"docs_pages.py: the server listed the tools {listed}, not TOOL_NAMES {TOOL_NAMES};"
            " the Tools page would not document every tool."
        )
    tools_md.write_text(tools_page(tools), encoding="utf-8")
    (docs_dir / "llms.txt").write_text(llms_txt(), encoding="utf-8")


def write_copies(docs_dir: Path, site_dir: Path) -> None:
    """Write each page's Markdown copy beside the page's index.html in `site_dir`."""
    for source, _, _ in PAGES:
        built = site_dir / page_dir(source)
        if not (built / "index.html").is_file():
            sys.exit(f"docs_pages.py: {built / 'index.html'} was not built; build the site first.")
        (built / "index.md").write_text(markdown_copy(source, docs_dir), encoding="utf-8")


def main() -> None:
    """Run the subcommand given on the command line."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    commands = parser.add_subparsers(dest="command", required=True)
    pages = commands.add_parser("pages", help="write the Tools page and llms.txt")
    copies = commands.add_parser("copies", help="write each built page's Markdown copy")
    for command in (pages, copies):
        command.add_argument("--docs-dir", type=Path, default=ROOT / "docs")
    copies.add_argument("--site-dir", type=Path, default=ROOT / "site")
    args = parser.parse_args()
    if args.command == "pages":
        write_pages(args.docs_dir)
    else:
        write_copies(args.docs_dir, args.site_dir)


if __name__ == "__main__":
    main()
